/*
 ************************************************************************************************* 
 * OrganicSmartHome [Version 1.0] is a framework for energy management in intelligent buildings
 * Copyright (C) 2011  Florian Allerding (florian.allerding@kit.edu)
 * 
 * 
 * This file is part of the OrganicSmartHome.
 * 
 * OrganicSmartHome is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or (at your option) any later version.
 * 
 * OrganicSmartHome is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with OrganicSmartHome.  
 * 
 * If not, see <http://www.gnu.org/licenses/>.
 * 
 *************************************************************************************************
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.13 at 04:00:26 PM MEZ 
//


package fal.rsh.driver.parser.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MieleIdMapping complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MieleIdMapping">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="smartHomeDeviceUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mieleId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MieleIdMapping", propOrder = {
    "smartHomeDeviceUUID",
    "mieleId"
})
public class MieleIdMapping {

    @XmlElement(required = true)
    protected String smartHomeDeviceUUID;
    protected int mieleId;

    /**
     * Gets the value of the smartHomeDeviceUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSmartHomeDeviceUUID() {
        return smartHomeDeviceUUID;
    }

    /**
     * Sets the value of the smartHomeDeviceUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSmartHomeDeviceUUID(String value) {
        this.smartHomeDeviceUUID = value;
    }

    /**
     * Gets the value of the mieleId property.
     * 
     */
    public int getMieleId() {
        return mieleId;
    }

    /**
     * Sets the value of the mieleId property.
     * 
     */
    public void setMieleId(int value) {
        this.mieleId = value;
    }

}
