/*
 ************************************************************************************************* 
 * OrganicSmartHome [Version 1.0] is a framework for energy management in intelligent buildings
 * Copyright (C) 2011  Florian Allerding (florian.allerding@kit.edu)
 * 
 * 
 * This file is part of the OrganicSmartHome.
 * 
 * OrganicSmartHome is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or (at your option) any later version.
 * 
 * OrganicSmartHome is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with OrganicSmartHome.  
 * 
 * If not, see <http://www.gnu.org/licenses/>.
 * 
 *************************************************************************************************
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.12 at 09:55:32 AM MESZ 
//


package fal.smartHomeLib.CBTypes.Simulation.Screenplay;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubjectAction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubjectAction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tick" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="periodicAction" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="periodicRefresh" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="actionType" type="{http://www.example.org/screenplay}ActionType"/>
 *         &lt;element name="deviceID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nextState" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="performAction" type="{http://www.example.org/screenplay}PerformAction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubjectAction", propOrder = {
    "tick",
    "periodicAction",
    "periodicRefresh",
    "actionType",
    "deviceID",
    "nextState",
    "performAction"
})
public class SubjectAction {

    protected long tick;
    @XmlElement(defaultValue = "false")
    protected boolean periodicAction;
    @XmlElement(defaultValue = "0")
    protected int periodicRefresh;
    @XmlElement(required = true)
    protected ActionType actionType;
    @XmlElement(required = true)
    protected String deviceID;
    protected boolean nextState;
    protected List<PerformAction> performAction;

    /**
     * Gets the value of the tick property.
     * 
     */
    public long getTick() {
        return tick;
    }

    /**
     * Sets the value of the tick property.
     * 
     */
    public void setTick(long value) {
        this.tick = value;
    }

    /**
     * Gets the value of the periodicAction property.
     * 
     */
    public boolean isPeriodicAction() {
        return periodicAction;
    }

    /**
     * Sets the value of the periodicAction property.
     * 
     */
    public void setPeriodicAction(boolean value) {
        this.periodicAction = value;
    }

    /**
     * Gets the value of the periodicRefresh property.
     * 
     */
    public int getPeriodicRefresh() {
        return periodicRefresh;
    }

    /**
     * Sets the value of the periodicRefresh property.
     * 
     */
    public void setPeriodicRefresh(int value) {
        this.periodicRefresh = value;
    }

    /**
     * Gets the value of the actionType property.
     * 
     * @return
     *     possible object is
     *     {@link ActionType }
     *     
     */
    public ActionType getActionType() {
        return actionType;
    }

    /**
     * Sets the value of the actionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *     
     */
    public void setActionType(ActionType value) {
        this.actionType = value;
    }

    /**
     * Gets the value of the deviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceID() {
        return deviceID;
    }

    /**
     * Sets the value of the deviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceID(String value) {
        this.deviceID = value;
    }

    /**
     * Gets the value of the nextState property.
     * 
     */
    public boolean isNextState() {
        return nextState;
    }

    /**
     * Sets the value of the nextState property.
     * 
     */
    public void setNextState(boolean value) {
        this.nextState = value;
    }

    /**
     * Gets the value of the performAction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the performAction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPerformAction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PerformAction }
     * 
     * 
     */
    public List<PerformAction> getPerformAction() {
        if (performAction == null) {
            performAction = new ArrayList<PerformAction>();
        }
        return this.performAction;
    }

}
