/*
 ************************************************************************************************* 
 * OrganicSmartHome [Version 1.0] is a framework for energy management in intelligent buildings
 * Copyright (C) 2011  Florian Allerding (florian.allerding@kit.edu)
 * 
 * 
 * This file is part of the OrganicSmartHome.
 * 
 * OrganicSmartHome is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or (at your option) any later version.
 * 
 * OrganicSmartHome is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with OrganicSmartHome.  
 * 
 * If not, see <http://www.gnu.org/licenses/>.
 * 
 *************************************************************************************************
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.17 at 03:50:28 PM MEZ 
//


package fal.smartHomeLib.CBTypes.Simulation.VirtualDevicesData;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deviceUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deviceType" type="{http://www.example.org/VirualIDeviceProfile}DeviceTypes"/>
 *         &lt;element name="deviceDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hasProfile" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="Intelligent" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="profileTicks" type="{http://www.example.org/VirualIDeviceProfile}ProfileTick" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deviceUUID",
    "deviceType",
    "deviceDescription",
    "hasProfile",
    "intelligent",
    "profileTicks"
})
@XmlRootElement(name = "DeviceProfile")
public class DeviceProfile {

    @XmlElement(required = true)
    protected String deviceUUID;
    @XmlElement(required = true)
    protected DeviceTypes deviceType;
    @XmlElement(required = true)
    protected String deviceDescription;
    protected boolean hasProfile;
    @XmlElement(name = "Intelligent")
    protected boolean intelligent;
    protected List<ProfileTick> profileTicks;

    /**
     * Gets the value of the deviceUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceUUID() {
        return deviceUUID;
    }

    /**
     * Sets the value of the deviceUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceUUID(String value) {
        this.deviceUUID = value;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceTypes }
     *     
     */
    public DeviceTypes getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceTypes }
     *     
     */
    public void setDeviceType(DeviceTypes value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the deviceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceDescription() {
        return deviceDescription;
    }

    /**
     * Sets the value of the deviceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceDescription(String value) {
        this.deviceDescription = value;
    }

    /**
     * Gets the value of the hasProfile property.
     * 
     */
    public boolean isHasProfile() {
        return hasProfile;
    }

    /**
     * Sets the value of the hasProfile property.
     * 
     */
    public void setHasProfile(boolean value) {
        this.hasProfile = value;
    }

    /**
     * Gets the value of the intelligent property.
     * 
     */
    public boolean isIntelligent() {
        return intelligent;
    }

    /**
     * Sets the value of the intelligent property.
     * 
     */
    public void setIntelligent(boolean value) {
        this.intelligent = value;
    }

    /**
     * Gets the value of the profileTicks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profileTicks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfileTicks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileTick }
     * 
     * 
     */
    public List<ProfileTick> getProfileTicks() {
        if (profileTicks == null) {
            profileTicks = new ArrayList<ProfileTick>();
        }
        return this.profileTicks;
    }

}
