/*
 ************************************************************************************************* 
 * OrganicSmartHome [Version 1.0] is a framework for energy management in intelligent buildings
 * Copyright (C) 2011  Florian Allerding (florian.allerding@kit.edu)
 * 
 * 
 * This file is part of the OrganicSmartHome.
 * 
 * OrganicSmartHome is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or (at your option) any later version.
 * 
 * OrganicSmartHome is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with OrganicSmartHome.  
 * 
 * If not, see <http://www.gnu.org/licenses/>.
 * 
 *************************************************************************************************
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.07.05 at 02:51:01 PM MESZ 
//


package fal.smartHomeLib.CBTypes.Configuration.ControllerBox;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FilePathes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FilePathes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="halConfigPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localObserverDataStoragePath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="simulationEngineConfigurationPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="logFileDirectory" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FilePathes", propOrder = {
    "halConfigPath",
    "localObserverDataStoragePath",
    "simulationEngineConfigurationPath",
    "logFileDirectory"
})
public class FilePathes {

    @XmlElement(required = true)
    protected String halConfigPath;
    @XmlElement(required = true)
    protected String localObserverDataStoragePath;
    @XmlElement(required = true)
    protected String simulationEngineConfigurationPath;
    @XmlElement(required = true)
    protected String logFileDirectory;

    /**
     * Gets the value of the halConfigPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHalConfigPath() {
        return halConfigPath;
    }

    /**
     * Sets the value of the halConfigPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHalConfigPath(String value) {
        this.halConfigPath = value;
    }

    /**
     * Gets the value of the localObserverDataStoragePath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalObserverDataStoragePath() {
        return localObserverDataStoragePath;
    }

    /**
     * Sets the value of the localObserverDataStoragePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalObserverDataStoragePath(String value) {
        this.localObserverDataStoragePath = value;
    }

    /**
     * Gets the value of the simulationEngineConfigurationPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimulationEngineConfigurationPath() {
        return simulationEngineConfigurationPath;
    }

    /**
     * Sets the value of the simulationEngineConfigurationPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimulationEngineConfigurationPath(String value) {
        this.simulationEngineConfigurationPath = value;
    }

    /**
     * Gets the value of the logFileDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogFileDirectory() {
        return logFileDirectory;
    }

    /**
     * Sets the value of the logFileDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogFileDirectory(String value) {
        this.logFileDirectory = value;
    }

}
