/*
 ************************************************************************************************* 
 * OrganicSmartHome [Version 1.0] is a framework for energy management in intelligent buildings
 * Copyright (C) 2011  Florian Allerding (florian.allerding@kit.edu)
 * 
 * 
 * This file is part of the OrganicSmartHome.
 * 
 * OrganicSmartHome is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or (at your option) any later version.
 * 
 * OrganicSmartHome is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with OrganicSmartHome.  
 * 
 * If not, see <http://www.gnu.org/licenses/>.
 * 
 *************************************************************************************************
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.24 at 08:41:52 AM MEZ 
//


package fal.smartHomeLib.CBTypes.Configuration.System;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assignedLocalOCUnit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assignedLocalOCUnit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="unitDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localControllerClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localObserverClassName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="localObserverParameter" type="{http://www.example.org/ConfigurationParameter}ConfigurationParameter"/>
 *         &lt;element name="localControllerParameter" type="{http://www.example.org/ConfigurationParameter}ConfigurationParameter"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assignedLocalOCUnit", propOrder = {
    "unitDescription",
    "localControllerClassName",
    "localObserverClassName",
    "localObserverParameter",
    "localControllerParameter"
})
public class AssignedLocalOCUnit {

    @XmlElement(required = true)
    protected String unitDescription;
    @XmlElement(required = true)
    protected String localControllerClassName;
    @XmlElement(required = true)
    protected String localObserverClassName;
    @XmlElement(required = true)
    protected ConfigurationParameter localObserverParameter;
    @XmlElement(required = true)
    protected ConfigurationParameter localControllerParameter;

    /**
     * Gets the value of the unitDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitDescription() {
        return unitDescription;
    }

    /**
     * Sets the value of the unitDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitDescription(String value) {
        this.unitDescription = value;
    }

    /**
     * Gets the value of the localControllerClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalControllerClassName() {
        return localControllerClassName;
    }

    /**
     * Sets the value of the localControllerClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalControllerClassName(String value) {
        this.localControllerClassName = value;
    }

    /**
     * Gets the value of the localObserverClassName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalObserverClassName() {
        return localObserverClassName;
    }

    /**
     * Sets the value of the localObserverClassName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalObserverClassName(String value) {
        this.localObserverClassName = value;
    }

    /**
     * Gets the value of the localObserverParameter property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationParameter }
     *     
     */
    public ConfigurationParameter getLocalObserverParameter() {
        return localObserverParameter;
    }

    /**
     * Sets the value of the localObserverParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationParameter }
     *     
     */
    public void setLocalObserverParameter(ConfigurationParameter value) {
        this.localObserverParameter = value;
    }

    /**
     * Gets the value of the localControllerParameter property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigurationParameter }
     *     
     */
    public ConfigurationParameter getLocalControllerParameter() {
        return localControllerParameter;
    }

    /**
     * Sets the value of the localControllerParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigurationParameter }
     *     
     */
    public void setLocalControllerParameter(ConfigurationParameter value) {
        this.localControllerParameter = value;
    }

}
