/*
 ************************************************************************************************* 
 * OrganicSmartHome [Version 1.0] is a framework for energy management in intelligent buildings
 * Copyright (C) 2011  Florian Allerding (florian.allerding@kit.edu)
 * 
 * 
 * This file is part of the OrganicSmartHome.
 * 
 * OrganicSmartHome is free software: you can redistribute it and/or modify it 
 * under the terms of the GNU General Public License as published by the Free Software Foundation, 
 * either version 3 of the License, or (at your option) any later version.
 * 
 * OrganicSmartHome is distributed in the hope that it will be useful, 
 * but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with OrganicSmartHome.  
 * 
 * If not, see <http://www.gnu.org/licenses/>.
 * 
 *************************************************************************************************
 */


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.14 at 04:39:54 PM MEZ 
//


package fal.smartHomeLib.CBTypes.Data.Observer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeSlot complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeSlot">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TimeSlotNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="timeFrom" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="timeTo" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="actions" type="{http://www.example.org/ObserverDataStorage}ObservedAction" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeSlot", propOrder = {
    "timeSlotNumber",
    "timeFrom",
    "timeTo",
    "actions"
})
public class TimeSlot {

    @XmlElement(name = "TimeSlotNumber")
    protected int timeSlotNumber;
    protected long timeFrom;
    protected long timeTo;
    protected List<ObservedAction> actions;

    /**
     * Gets the value of the timeSlotNumber property.
     * 
     */
    public int getTimeSlotNumber() {
        return timeSlotNumber;
    }

    /**
     * Sets the value of the timeSlotNumber property.
     * 
     */
    public void setTimeSlotNumber(int value) {
        this.timeSlotNumber = value;
    }

    /**
     * Gets the value of the timeFrom property.
     * 
     */
    public long getTimeFrom() {
        return timeFrom;
    }

    /**
     * Sets the value of the timeFrom property.
     * 
     */
    public void setTimeFrom(long value) {
        this.timeFrom = value;
    }

    /**
     * Gets the value of the timeTo property.
     * 
     */
    public long getTimeTo() {
        return timeTo;
    }

    /**
     * Sets the value of the timeTo property.
     * 
     */
    public void setTimeTo(long value) {
        this.timeTo = value;
    }

    /**
     * Gets the value of the actions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObservedAction }
     * 
     * 
     */
    public List<ObservedAction> getActions() {
        if (actions == null) {
            actions = new ArrayList<ObservedAction>();
        }
        return this.actions;
    }

}
